# -*- mode: ruby -*-
# vi: set ft=ruby :

# Every Vagrant development environment requires a box. You can search for
# boxes at https://atlas.hashicorp.com/search.
BOX_IMAGE = "ubuntu/xenial64"
NODE_COUNT = 3

Vagrant.configure("2") do |config|
  (1..NODE_COUNT).each do |i|
    config.vm.define "h#{i}" do |subconfig|
      subconfig.vm.synced_folder "../Ethereum-Bench-stack", "/srv/"
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "h#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i*10 + 1}"

      if i == 1
        subconfig.vm.provision "shell", inline: <<-SHELL
          bash ./bootstrap-salt.sh -x python3 -D -M -J '{"open_mode":true,"auto_accept":true,"file_roots":{"base":["/srv/salt","/srv/formulas/node-formula","/srv/formulas/docker-formula","/srv/formulas/monitoring-formula"]}}' -j '{"mine_functions":{"parity_authority":[{"mine_function":"paritymanager.get_accounts_by_meta"},"role","authority"],"datapath_ip":[{"mine_function":"network.ip_addrs"},"enp0s8"],"parity_enode":[{"mine_function":"paritymanager.get_enode"}],"parity_user":[{"mine_function":"paritymanager.get_accounts_by_meta"},"role","user"]},"mine_interval":1,"rejected_retry":true}'  -A 10.0.0.11
        SHELL
      else
        subconfig.vm.provision "shell", inline: <<-SHELL
          bash ./bootstrap-salt.sh -x python3 -D  -j '{"mine_functions":{"parity_authority":[{"mine_function":"paritymanager.get_accounts_by_meta"},"role","authority"],"datapath_ip":[{"mine_function":"network.ip_addrs"},"enp0s8"],"parity_enode":[{"mine_function":"paritymanager.get_enode"}],"parity_user":[{"mine_function":"paritymanager.get_accounts_by_meta"},"role","user"]},"mine_interval":1,"rejected_retry":true}'  -A 10.0.0.11
        SHELL
      end
    end

    config.ssh.username = 'vagrant'

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
    end

    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"

    config.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
      sudo add-apt-repository -y ppa:ethereum/ethereum
      sudo apt-get update
      sudo apt-get install git curl --yes
      wget -O bootstrap-salt.sh https://bootstrap.saltstack.com 
      sudo apt-get install ethereum -y
      sudo apt-get install solc -y
    SHELL
  end
end