# -*- mode: ruby -*-
# vi: set ft=ruby :

# Every Vagrant development environment requires a box. You can search for
# boxes at https://atlas.hashicorp.com/search.
BOX_IMAGE = "ubuntu/bionic64"
NODE_COUNT = 3

Vagrant.configure("2") do |config|
  (0..NODE_COUNT-1).each do |i|
    config.vm.define "h#{i}" do |subconfig|
      subconfig.vm.synced_folder "../Ethereum-Bench-stack", "/srv/"
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "h#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i*10 + 11}"

      subconfig.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install git curl --yes
      wget -O bootstrap-salt.sh https://bootstrap.saltstack.com 
      SHELL

      if i == 0
        subconfig.vm.provision "shell", inline: <<-SHELL
          
          bash ./bootstrap-salt.sh  -x python3 -D -M -J '{"open_mode":true,"auto_accept":true,"file_roots":{"base":["/srv/salt","/srv/formulas/node-formula","/srv/formulas/docker-formula","/srv/formulas/monitoring-formula"]}}' -j '{"mine_functions":{"parity_authority":[{"mine_function":"paritymanager.get_accounts_by_meta"},"role","authority"],"datapath_ip":[{"mine_function":"network.ip_addrs"},"enp0s8"],"parity_enode":[{"mine_function":"paritymanager.get_enode"}],"parity_user":[{"mine_function":"paritymanager.get_accounts_by_meta"},"role","user"]},"mine_interval":1,"rejected_retry":true}'  -A 10.0.0.11 stable 2019.2.3 
        SHELL
      else
        subconfig.vm.provision "shell", inline: <<-SHELL
          
          bash ./bootstrap-salt.sh  -x python3 -D  -j '{"mine_functions":{"parity_authority":[{"mine_function":"paritymanager.get_accounts_by_meta"},"role","authority"],"datapath_ip":[{"mine_function":"network.ip_addrs"},"enp0s8"],"parity_enode":[{"mine_function":"paritymanager.get_enode"}],"parity_user":[{"mine_function":"paritymanager.get_accounts_by_meta"},"role","user"]},"mine_interval":1,"rejected_retry":true}'  -A 10.0.0.11 stable 2019.2.3 
        SHELL
      end
    end

    config.ssh.username = 'vagrant'

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
    end

  
  end
end